# Generated by Django 4.0.6 on 2023-08-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('inicio_rango_fecha_ejecucion', models.DateField()),
                ('final_rango_fecha_ejecucion', models.DateField()),
                ('estado', models.CharField(choices=[('1', 'Activa'), ('0', 'Inactiva')], default='1', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_registro', models.CharField(default='1', max_length=200)),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Acta',
                'db_table': 'Actas',
            },
        ),
        migrations.CreateModel(
            name='Oficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Oficial',
                'verbose_name_plural': 'Oficiales',
                'db_table': 'Oficiales',
            },
        ),
    ]
