# Generated by Django 4.0.6 on 2023-08-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0002_acta_oficial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acta',
            options={'verbose_name': 'Acta', 'verbose_name_plural': 'Actas'},
        ),
        migrations.AddField(
            model_name='oficial',
            name='cedula',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
