# Generated by Django 4.0.6 on 2023-08-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0003_alter_acta_options_oficial_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficial',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
    ]
