# Generated by Django 4.0.6 on 2023-08-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0006_customuser_oficial_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
