# Generated by Django 4.0.6 on 2023-08-09 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionpedidos', '0008_alter_oficial_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='usuario_registro',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
