# Generated by Django 4.0.6 on 2023-08-10 15:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionpedidos', '0009_alter_acta_usuario_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Este campo debe tener 8 dígitos.'), django.core.validators.MaxLengthValidator(limit_value=8, message='Este campo debe tener 8 dígitos.')])),
                ('fecha_ejecucion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpedidos.acta')),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionpedidos.actividad')),
                ('id_oficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_as_id_oficial', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_as_usuario_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
            },
        ),
    ]
