# Generated by Django 4.0.6 on 2023-08-10 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0010_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Este campo debe tener 8 dígitos.'), django.core.validators.MaxLengthValidator(limit_value=8, message='Este campo debe tener 8 dígitos.')]),
        ),
    ]
