# Generated by Django 4.0.6 on 2023-08-11 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0014_rename_id_acta_pedido_acta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000, message='Este campo debe tener 8 dígitos.'), django.core.validators.MaxValueValidator(99999999, message='Este campo debe tener 8 dígitos.'), django.core.validators.RegexValidator('^\\d{8}$', message='Este campo debe tener exactamente 8 dígitos.')]),
        ),
    ]
